### ISSUE TITLE
Sleep Timer - pause after time period.

### ISSUE THREAD

**Issue by rTfact** [JasonLG1979/gnome-shell-extensions-mediaplayer#401]
I often want to play audio for a certain amount of time, but so far haven't found an easy way to do this
on my Linux desktop (or any other desktop OS).
Workaround is to use mpris2:
$ sleep 60 && qdbus org.mpris.MediaPlayer2.rhythmbox /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Pause
(or echo the command to "at <time>"):
$ echo "qdbus ..." | at now + 5 min

Could we have some way of adding a timer to the pause event?

-- More or less relevant information --
On an iOS device it's possible to use a std. timer event to stop playback.
On Android there are separate apps for this like "Sleep Timer".

Ideally I would have a playlist, where I could set start and end times.
Don't know if something like SMIL format would work, but doesn't seem
like any music player is using it.
https://en.wikipedia.org/wiki/Synchronized_Multimedia_Integration_Language
Considering using Reveal.js

**Comment by JasonLG1979** [comment]
The basic idea of a timer works much the same in Gjs, or just about every other UI toolkit bindings or language . You set a timeout for a certain amount of time and then call a function.

I'm not sure if I want to add a sleep timer to this extension. My issues with it are:

1. It's maybe a little out of scope. If you want a sleep timer for your chosen media player it should probably be implemented in the actual player.

2. The natural place to configure said sleep timer is the extension settings, which seems cumbersome since it's not accessible directly from the extensions main UI and I'm not adding a settings button just for one feature since the rest of the settings are basically set it once and never open the settings again.

3. The idea is simple but implementing could get complicated fast. Is it a global timer? Is it by player? and so on and so on.

**Comment by rTfact** [comment]
Thanks for the quick and thorough reply - no doubt you right in your assessment.
1. There are a lot of players around, and I only did a fairly quick search, but I'm a little surprised no one has made a sleep timer part of the UI or plugin. VLC has a plugin, but it's not maintained and doesn't work any more.
2. Didn't think much about how it should work, but you are right. This could be a small app or plugin. Something like gnome-schedule could be used as is or even added to. I was just happy to see that MPRIS provided a simple way to script a solution. I can even just use a simple shell cmd. Maybe use playerctl:
https://github.com/acrisci/playerctl
3. Well if it was to be a "Sleep Timer", then it would be global, I guess, but yes then the wish for more features starts to appear.

Thanks again - great shell extension.

**Comment by JasonLG1979** [comment]
It might be a great extension in it's own right. It would not be complicated to just implement it as a separate extension. Basically you'd just walk the mpris players if any when the time came and either fire of a pause, stop, or quit call to each of them. The settings would basically just be on/off and a time.
