### ISSUE TITLE
Gnome Music close immediately

### ISSUE THREAD

**Issue by threetopia** [JasonLG1979/gnome-shell-extensions-mediaplayer#409]
Hello,
Got problem on openSUSE gnome-music app. The app immediately closed after launch.
Here what I got when I launch it from terminal
`Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/gnomemusic/mpris.py", line 73, in on_method_call
    result = getattr(self, method_name)(*args)
  File "/usr/lib/python3.4/site-packages/gnomemusic/mpris.py", line 732, in GetAll
    % interface_name)
Exception: ('org.mpris.MediaPlayer2.GnomeMusic', 'This object does not implement the org.mpris.MediaPlayer2.ExtensionSetRatings interface')`
This only happen when Media player indicator turned on, and the problem is not appear on previous version (don't know which version is, but the problem not appear on version that I can click the album cover to make it bigger).
May all of this information is useful. Thank you :)

**Comment by JasonLG1979** [comment]
That's their fault. The problem is here https://github.com/GNOME/gnome-music/blob/master/gnomemusic/mpris.py#L703-L707. They are purposely raising an exception when they git hit with an unknown interface name. Since according to the main author of the spec extending the mpris interface is OK they should just ignore interfaces they don't implement.

**Comment by JasonLG1979** [comment]
For now I'll just blacklist them from that interface.

**Comment by JasonLG1979** [comment]
To illiterate:

I'm blaming Gnome Music for throwing an Exception(error) when they are asked for properties of an interface which they do not implement and thus self destructing themselves. As I said in the original bug report, according to the lead author of the MPRIS spec extending the MPRIS interface with custom extensions is perfectly fine as per https://lists.freedesktop.org/archiv...q4/000054.html . So instead of self destructing when they are asked for properties of an interface which they do not implement they should just return an empty array.

**Comment by JasonLG1979** [comment]
From https://github.com/GNOME/gnome-music/blob/master/gnomemusic/mpris.py#L699-L707

```python
        elif interface_name == 'org.freedesktop.DBus.Properties':
            return {}
        elif interface_name == 'org.freedesktop.DBus.Introspectable':
            return {}
        else:
            raise Exception(
                'org.mpris.MediaPlayer2.GnomeMusic',
                'This object does not implement the %s interface'
                % interface_name)
```

Should simply be:

```python
        else:
            return {}
```

**Comment by lexruee** [comment]
@JasonLG1979 
I guess the best thing to do is to file a bug report to GNOME Music along with a patch:

[1] Project Website: https://wiki.gnome.org/Apps/Music/Resources
[2] Bug Reporting Page: https://bugzilla.gnome.org/enter_bug.cgi?product=gnome-music

**Comment by JasonLG1979** [comment]
> I guess the best thing to do is to file a bug report (along with a patch) to GNOME Music:
> 
> [1] Project Website: https://wiki.gnome.org/Apps/Music/Resources
> [2] Bug Reporting Page: https://bugzilla.gnome.org/enter_bug.cgi?product=gnome-music

Be my guest. I've filed bug reports against their MPRIS implementation before and they don't fix the simplest things. I'll stick to Lollypop and Pithos as far as working on player implementations. 

This commit should stop any other boneheads from throwing errors:
https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/commit/ddfa19a04eb878f003ceaacffc55095e854275cc

**Comment by nekoexmachina** [comment]
That is a little bit disappointing. However, while I like gnome-music UI, some of their decisions on how does it work seem extremely out of place and-or plainly wrong.

**Comment by JasonLG1979** [comment]
> That is a little bit disappointing. However, while I like gnome-music UI, some of their decisions on how does it work seem extremely out of place and-or plainly wrong.

It's not about wrong or right as far as I don't think it's intentional. The MPRIS spec is kinda confusing and vague IMHO. Doing it right is way more complicated then it should be. Their are definitely parts of the spec that should be clarified and improved.
