### ISSUE TITLE
Indicator: Elapsed time

### ISSUE THREAD

**Issue by roizcorp** [JasonLG1979/gnome-shell-extensions-mediaplayer#430]
This extension is my main goto for handling my music playback
I find it useful to add the track's elapsed time in the indicator so I could see the time w/o opening the widget.
I think that here also we should apply the orientation in one of the following approaches:

1. Center,Left,Right
2. Part of the indicator format i.e. "%time %artist - %track"

**Comment by JasonLG1979** [comment]
I'd say part of the indicator format. Something like trackLength and trackTime which already exist as internally properties. It's just a matter of exposing them in the panel logic and doing a bit of clock math.

So {trackArtist - }{trackTitle}{trackTime / }{trackLength} would get you something like "My Favorite Band - My Favorite song 2:03 / 3:45"

**Comment by roizcorp** [comment]
the indicator format works right away however the time format is not in minutes i.e. instead of 1:10 it shows 70

**Comment by JasonLG1979** [comment]
I'll have to add a function to do some modulus math(clock math) to convert it to hh:mm:ss

**Comment by roizcorp** [comment]
you're the best! 
many thanks!

**Comment by roizcorp** [comment]
I suggest to handle with and without hh, most of songs will not use the hour unit while the real estate is precious

**Comment by JasonLG1979** [comment]
> I suggest to handle with and without hh, most of songs will not use the hour unit while the real estate is precious

I can make so that if there is no hours value it will not take up space.

**Comment by JasonLG1979** [comment]
Something like this should do it:

```js
  var formatTime = function(s) {
    let h = Math.floor(s / 3600);
    s -= h * 3600;
    let m = Math.floor(s / 60);
    s -= m * 60;
    if (s < 10) {
      s = '0' + s;
    }
    if (m < 10 && h > 0) {
      m = '0' + m;
    }
    if (h > 0) {
      h = h + ':';
    }
    else {
      h = '';
    }
    return h + m + ':' + s
  };
```

The time string would take up as little space as possible. For example 12:23:14, 1:43:72, 10:25, 3:37,  0:43,

**Comment by JasonLG1979** [comment]
The resulting names will probably be trackDuration and trackPosition. I'll get it added tomorrow sometime. I got to get some sleep before work ATM.

**Comment by roizcorp** [comment]
Nice!

**Comment by JasonLG1979** [comment]
@roizcorp there you go.

An example would be {trackArtist - }{trackTitle | }{trackPosition / }{trackDuration}

Which would get you this:

![screenshot from 2017-10-31 20-17-07](https://user-images.githubusercontent.com/6667703/32255903-a0757a76-be79-11e7-9ff0-173f9c34514e.png)

It's not super accurate though because of the way position works in MPRIS. Many props use signals to tell when they have changed so we can update things accordingly. Position does not emit a changed signal as per spec. So our position is just an incremental 1 sec timeout. It's not actually tied to the player's time. So it may drift or be off by a sec at times. There's really not much we can do about that besides querying the player every sec, which isn't really an option.

**Comment by roizcorp** [comment]
That's perfect, thank you
