### ISSUE TITLE
Gnome-Shell 3.26.2 crashes when attaching/removing storage

### ISSUE THREAD

**Issue by daniel-wtd** [JasonLG1979/gnome-shell-extensions-mediaplayer#439]
Hey,

this is a weird one, I assume. After enabling your extension (which looks and feels very cool) I am seeing the following issue:

### Current Behaviour
Gnome Shell crashes/resets, when a storage device is attached/removed.
This can be either a thumb drive, external disk or sd card.

### Wanted behaviour
Attaching and removing a thumb drive does not crash the shell.

### Reproducing
| The below works in xorg and wayland session
1. Install Fedora 27
2. Update to latest packages
3. Install extension from https://extensions.gnome.org/extension/55/media-player-indicator/
4. Attach a usb drive or another removable storage
5. find yourself at the login screen
6. login
7. remove the same removable storage from above
8. find yourself at the login screen
9. Disable the extension via extensions.gnome.org or tweak-tool
10. Now 4 and 7 are working, without crashing the gnome-shell

Unfortunately I am not aware, where to find related logs or debug entries.
If you need more input or testing from my side, please give me an @mention and I'll do whats needed to help you!

**Information:**
OS: Fedora 27
gnome-shell: gnome-shell-3.26.2-3.fc27.x86_64
kernel: 4.14.14-300.fc27.x86_64

**Comment by JasonLG1979** [comment]
That is strange, this extension has nothing to do with drives, attached or otherwise except to load the actual extension and GNOME Shell takes care of that ofc. The extension itself doesn't interact all with any drive.

I happen to be a Fedora user also so my machine is also running completely up to date version of Fedora 27 atm. (just made sure with ```sudo dnf clean all && sudo dnf update -y```) Anyway I just wnet though the steps you provided to reproduce your bug and no crashes for me so far.

I have noticed a lot of non-fatal (for me at least) crashes in GNOME Shell recently. The logs say a bunch of stuff like this for example:

```Object Meta.WindowActor (0x55922f063760), has been already finalized. Impossible to get any property from it.```

Followed by a stack trace. But I get those regardless of what extensions are installed and/or enabled. I've tried to find out what the problem is but it's unclear. From what I can tell the latest Gjs update may have screwed things up, or at least exposed some bugs/improper handling of signals in GNOME Shell. Namely it appears to me that maybe objects are being destroyed before signal handlers are disconnected?

In any event you can look at the logs with the GUI app Logs. It's installed by default. Click on the "All" tab and search for "mediaplayer@patapon.info" and you'll see any error related to the extension. Otherwise look though all of the "All" tab to see if you can see what took down the Shell?

**Comment by daniel-wtd** [comment]
Hey thanks for the fast reply :)

After your comment I tried to reproduce again. It seems like some security mechanism in gnome has disabled all of my extensions and the steps above are not quite correct.

After another run I can say: Nothing wrong with the extension.
The culprit is 🥁  🥁  🥁  https://extensions.gnome.org/extension/8/places-status-indicator/, which makes actually more sense.

Sorry for the wrong issue. It can be closed. I'll post another one to fmuellner.

**Comment by daniel-wtd** [comment]
relevant bug: https://gitlab.gnome.org/GNOME/gnome-shell-extensions/issues/49

**Comment by JasonLG1979** [comment]
Yep, just tried ```proxy.run_dispose()``` on my DBus proxies in the extension and I got some wicked errors. Seems to me you're not suppose to use that method in bindings to garbage collected languages like js. I've never used it once with the Python bindings either? Me thinks the garbage collector is suppose to take care of the final disposal of objects?

**Comment by JasonLG1979** [comment]
GNOME Shell is littered with [```run_dispose()```](https://github.com/GNOME/gnome-shell/search?l=JavaScript&q=run_dispose%28%29&type=&utf8=%E2%9C%93)

Could be the reason for all the other crashes I'm seeing?

**Comment by JasonLG1979** [comment]
I'm going to leave this open though for now. I'm sure you won't be that last to have an extension take down the Shell.

**Comment by daniel-wtd** [comment]
thanks a lot 👍

**Comment by JasonLG1979** [comment]
https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/blob/master/README.md
