### ISSUE TITLE
Make cover art in panel resizable.

### ISSUE THREAD

**Issue by ghost** [JasonLG1979/gnome-shell-extensions-mediaplayer#443]
I'm using dash-to-panel which makes the panel a good bit bigger than the default top bar, hence the cover art doesn't span the full thickness of the panel. It'd be nice if the cover art was resizable so it didn't look too small on thicker panels.

**Comment by JasonLG1979** [comment]
The cover art uses the built in "panel-button" style-class it's size is determined by whatever theme you choose, so therefore it remains consistent with the rest of the desktop theme. I have no plans to change this to work around an inconstancy caused by interactions with other extensions. Extensions can and do interact in undesirable ways, that's just the nature of the beast when there is no API. In the absence of an API my test case is how the the extension looks and/or behaves with no other extension enabled.

**Comment by JasonLG1979** [comment]
https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/blob/master/README.md
