### ISSUE TITLE
Add explicit support for gnome shell 3.28

### ISSUE THREAD

**Issue by drakkar1969** [JasonLG1979/gnome-shell-extensions-mediaplayer#453]
Would it be possible to explicitly include gnome shell 3.28 in the list of supported shell versions in `metadata.json`? AUR Arch package will not install on gnome shell 3.28, as it checks compatible shell versions in the metadata file (and 3.28 is not included)

**Comment by cookiengineer** [comment]
This issue would be fixed with this pull request: https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/pull/454

I also flagged the AUR package as orphaned, so hopefully it will be available for adoption soon, as XZS seems to not have time to maintain it anymore (since October 2017).

**Comment by dffischer** [comment]
Package maintainer for the AUR here. I am usually only shipping out the releases tagged here on Github by the author. As the current master branch already contains the mentioned changes and the package auto-updates to that on build, you may simply rebuild and install it now.

As other maintainers likely track the releases, too, I nonetheless like to hereby kindly ask @JasonLG1979 to mark a new release so that users installing via package managers also automatically receive the update. Thanks.

**Comment by JasonLG1979** [comment]
Done

**Comment by dffischer** [comment]
The extensions.gnome.org site is a fine interface. As far as I know, it installs extensions for the current user. When the extension is installed to the system globally, having it lying around once is enough for all users to activate it.

Thank you for the release. I will make sure to check out your other extension.

**Comment by dffischer** [comment]
In addition, I think this issue may well be closed as the original problem was fixed by the merge of #454 .
