### ISSUE TITLE
Needs Update for GNOME 3.32

### ISSUE THREAD

**Issue by mon0theist** [JasonLG1979/gnome-shell-extensions-mediaplayer#476]
3.32 is out, which of course has broken lots of extensions, including this one

Needs update for GNOME 3.32 pretty please

**Comment by corebots** [comment]
i second this request.

**Comment by corebots** [comment]
does your other extension have a feature to show the song info in the panel like this one? (gives an error on 3.32 now also)

**Comment by JasonLG1979** [comment]
> does your other extension have a feature to show the song info in the panel like this one? (gives an error on 3.32 now also)

No, not at the moment. I'm in the process of porting some of the features of this extension to the newer one. The plan is to cherry pick feature ideas from this extension and then retire it. On the MPRIS interface side it's a matter of exposing the features/functionality that the most players expose *correctly* and having a way to fail/fallback gracefully. For example I'm currently working on adding volume control to the newer extension and I have found a reasonably reliable way to test if a player has a working volume control via MPRIS. The general idea is that if volume works in a player's MPRIS interface you get a volume control if not (like in the case of Spotify) the volume control is hidden(since it would be useless anyway).

![Screenshot from 2019-03-19 08-47-53](https://user-images.githubusercontent.com/6667703/54610890-ece12680-4a23-11e9-9d75-767b6571b7b7.png)

There's no need for a user pref to hide or show volume controls. I'd like to do the same with many of the user prefs. At least the ones directly tied to the MPRIS interfaces. Features like showing the song info in the panel will need to be reviewed and decisions will have to be made if they are worth a user setting. I'd like to keep user settings to an absolute minimum if there are any at all.

**Comment by JasonLG1979** [comment]
I'll have to do some kind of poll or something to get user input as far as how to proceed with the cherry picking. At the very least I need to get an idea of what are the most used and important features as far as the users are concerned. It would be a pretty shady move to just be like, "...OK Users, this thing is retired. Here's a replacement that basically works but has like half of the features and functionality you used and loved from the thing it's replacing."

I don't have any real set plan or time frame at the moment. I do this as a hobby so real life is more important. How much gets done and how fast depends on family schedules, how much mandatory overtime I have to work at my paying gig and of course how much help I get from other people.

**Comment by mon0theist** [comment]
So just to confirm, we should not expect any updates on this Extension and instead transition to your other one at some point?

**Comment by JasonLG1979** [comment]
> So just to confirm, we should not expect any updates on this Extension and instead transition to your other one at some point?

It'll be a bit at least before I push any updates personally to this extension if any but I wouldn't turn down any useful pull requests.

At some point in the undetermined future the idea is that yes, this extension will be retired at least in the sense that I will not be maintaining it. That doesn't mean it ceases to exist necessarily though. It is free software. Nothing is stopping anyone from doing a real fork or asking for maintainership from me.

**Comment by corebots** [comment]
I would be curious about your user research, to me the only point is to have the playback status + current band/album/song info always visible in the top bar, in addition, the middle click for play/pause is very nice. I would welcome a) crawling text if the whole song title doesn't fit into the set width, b) display previous/pause/next controls on hover instead of text, perhaps with the album art. That's it. If one needs to click somewhere to display these info than the default shell notification area has this already built in. Anyways, thank you for all the work.

**Comment by fbruetting** [comment]
Interesting to hear about that other extension. What exactly is the benefit of this extension, compared to the already existing song entry in this Gnome shell overview panel (when you click on the date/time in the top bar)? If something is missing there, can’t that maybe contributed to Gnome shell directly?

I for example like having the song metadata in the left side of the top bar, because there is a lot of free space otherwise, it doesn’t disturb (please no crawling text!) and I often want to see which song is currently played, so it saves me clicks to get to that (which in turn saves time and leads to less distraction).

**Comment by JasonLG1979** [comment]
>But what exactly is the benefit of this extension

This extension predates the stock MPRIS widget, and is a much more robust implementation. The newer extension is even more robust and more error tolerant. 

>can’t that maybe contributed to Gnome shell directly?

They're pretty happy with what they have and in my experience are not very open to outside contributions.

**Comment by JasonLG1979** [comment]
Here's a list of flaws in the stock MPRIS widget off the top of my head:

Objective flaws:

1. It's not handicap accessible. The screen reader does not read the contents of the stock MPRIS widget. My latest MPRIS extension is. The screen reader will speak aloud the player's name, artist name and track title when the widget is selected or moused over.

2. It does not handle errors at all when setting the cover art image which can result in the previous cover being shown in the event of an error. Both of my MPRIS extensions handle invalid urls and errors correctly and set the cover image to a fallback icon.

3. It does not handle players that can not pause. In both of my extensions if a player can not pause but is playing it is assumed that the player can stop so a stop button is shown.

4. It does not handle multiple instances of the same player. If you are running multiple instances and you try to raise one of them it often times raises the wrong instance. My newest extension handles multiple instances very well.

5. It does not handle cases where there is no "xesam:artist" metadata. There are many other metadata fields besides "xesam:artist" that a track may have that for display purposes are roughly equivalent to "artist". ( "xesam:albumArtist", "xesam:composer", "xesam:lyricist", "rhythmbox:streamTitle").  My newest extension tries it's best to display something for an artist in the widget instead of just "Unknown artist" when there is no "xesam:artist" metadata.

Subjective flaws:

1. It's buried in the notification area.  IMHO the whole point of MPRIS is to be a universal replacement of sorts for media player tray icons. I don't like to use the word "intuitive" when it comes to UI design, but It makes more sense to me to put MPRIS controls in a button in the panel where a tray icon would traditionally be.

Improvements:

In addition to the overcome flaws in the stock MPRIS widget:

1. My newest MPRIS extension also has very useful mouse actions and keyboard shortcuts. https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/wiki/User-Guide

2. My newest extension works flawlessly with the Spotify desktop player (with the exception of volume controls) Normal install, snap or flatpak it doesn't matter. Your mileage may vary with the stock MPRIS widget and Spotify.
